# Generated by Django 3.1.7 on 2021-03-04 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('details', models.TextField(blank=True, default='Es un detalle por defecto.', null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('message', models.CharField(blank=True, default='Es un mensaje por defecto.', max_length=20, null=True)),
            ],
        ),
    ]
