# Generated by Django 3.1.7 on 2021-03-05 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='details',
            field=models.TextField(blank=True, default='Escribe la descripcion.', null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='message',
            field=models.CharField(blank=True, default='Escribe un mensaje.', max_length=20, null=True),
        ),
    ]
